In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "
print("capitalise():",A.capitalize())


capitalise():  koneru lakshmaiaha educational foundation 


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("casefold():",A.casefold())


casefold():  koneru lakshmaiaha educational foundation 


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("center():",A.center(60,'*'))


center(): ******** KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION *********


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("count():",A.count("A"))


count(): 7


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("find():",A.find("EDUCATIONAL"))


find(): 20


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("index():",A.index("FOUNDATION"))


index(): 32


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("islower():",A.islower())


islower(): False


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "
print("isupper():",A.isupper())


isupper(): True


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "

print("join():", "-".join(A))


join():  -K-O-N-E-R-U- -L-A-K-S-H-M-A-I-A-H-A- -E-D-U-C-A-T-I-O-N-A-L- -F-O-U-N-D-A-T-I-O-N- 


In [ ]:
A=" KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION "
print("capitalise():",A.capitalize())
print("casefold():",A.casefold())
print("center():",A.center(60,'*'))
print("count():",A.count("A"))
print("find():",A.find("EDUCATIONAL"))
print("index():",A.index("FOUNDATION"))
print("islower():",A.islower())
print("isupper():",A.isupper())
print("join():", "-".join(A))
print("lower():",A.lower())
print("replace():",A.replace("FOUNDATION","UNIVERSITY"));
print("swapcase():",A.swapcase())
print("title():",A.title())
print("upper():",A.upper())
print("zfill():",A.zfill(60))

capitalise():  koneru lakshmaiaha educational foundation 
casefold():  koneru lakshmaiaha educational foundation 
center(): ******** KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION *********
count(): 7
find(): 20
index(): 32
islower(): False
isupper(): True
join():  -K-O-N-E-R-U- -L-A-K-S-H-M-A-I-A-H-A- -E-D-U-C-A-T-I-O-N-A-L- -F-O-U-N-D-A-T-I-O-N- 
lower():  koneru lakshmaiaha educational foundation 
replace():  KONERU LAKSHMAIAHA EDUCATIONAL UNIVERSITY 
swapcase():  koneru lakshmaiaha educational foundation 
title():  Koneru Lakshmaiaha Educational Foundation 
upper():  KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION 
zfill(): 00000000000000000 KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION 


In [ ]:
import numpy as np
n = np.array([1,2,3,4,5,6])
print(n.shape)

(6,)


In [ ]:
import numpy as np
n = np.array([1,2,3,4,5,6])
print(n.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
n = np.array([1,2,3,4,5,6])
for x in n:
  print(x)

1
2
3
4
5
6


In [ ]:
import numpy as np #array
p = np.array([[1,2,3],[4,5,6],[7,8,9]])
for a in p:
  print(a)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
import numpy as np #concatenate or combining
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n3 = np.concatenate((n1,n2))
print(n3)

[1 2 3 4 5 6]


In [ ]:
import numpy as np #split
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
n3 = np.concatenate((n1,n2))

print(np.array_split(n3,4))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
x = np.array_split(n1,2)
print(x)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
x = np.array_split(n1,2)
print(x[0])

[[1 2 3]]


In [ ]:
import numpy as np   #Searching in a array
n1 = np.array([4,2,3,4])
p = np.where(n1==4)
print(p)

(array([0, 3]),)


In [ ]:
import numpy as np   #Sorting of a array
n1 = np.array([4,2,3,1])
p = np.sort(n2)
print(p)

[5 6 7 8]


In [ ]:
import numpy as np  #sum of all elements
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(np.sum([n1,n2]))

36


In [ ]:
import numpy as np    #adding the n1 as one and the other as another
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(np.sum([n1,n2],axis=1))

[10 26]


In [ ]:
import numpy as np    #adding with above and below elements
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(np.sum([n1,n2],axis=0))

[ 6  8 10 12]


In [ ]:
import numpy as np
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(np.subtract(n2, n1))

[4 4 4 4]


In [ ]:
import pandas as pd
data = {'apples': [3,2,0,1] , 'bananas': [0,3,7,2]}
print(pd.DataFrame(data))

   apples  bananas
0       3        0
1       2        3
2       0        7
3       1        2


In [ ]:
import pandas as pd
data = {'col_1': [3,2,1,0] , 'col_2': ['a','b','c','d']}
pd.DataFrame.from_dict(data)

,col_1,col_2
0,3,a
1,2,b
2,1,c
3,0,d


In [ ]:
import pandas as pd
data = {'row_1': [3,2,1,0] , 'row_2': ['a','b','c','d']}
pd.DataFrame.from_dict(data,orient='index')

,0,1,2,3
row_1,3,2,1,0
row_2,a,b,c,d


In [ ]:
import pandas as pd
data = {'row_1': [3,2,1,0] , 'row_2': ['a','b','c','d']}
pd.DataFrame.from_dict(data,orient='index',columns = ['A','B','C','D'])

,A,B,C,D
row_1,3,2,1,0
row_2,a,b,c,d


In [ ]:
import pandas as pd
df = pd.read_csv("/content/Iris -.csv")
print(df)


      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
import pandas as pd



In [ ]:
pd.read_json('dataset.json')

In [ ]:
import pandas as pd
import numpy as np
#Sample dataset
df = pd.DataFrame({'Age': [25,30,np.nan,40,35],
    'Department': ['HR', 'Finance', 'Finance',np.nan, 'IT']})
print(df)
#Mean for numeric
df['Age'] = df['Age'].fillna(df['Age'].mean())
#Mode for categorical
df['Department']= df['Department'].fillna(df['Department'].mode()[0])
print(df)

    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT


In [ ]:
import pandas as pd
import numpy as np
#Sample dataset
df = pd.DataFrame({'Age': [25,30,np.nan,40,35],
    'Department': ['HR', 'Finance', 'Finance',np.nan, 'IT']})
#Display Original Dataset
print("Original Dataset(With Missing Values): ")
print(df)
df_ffill = df.copy()
df_ffill.ffill(inplace=True)
print(df_ffill)

Original Dataset(With Missing Values): 
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
2  30.0    Finance
3  40.0    Finance
4  35.0         IT


In [ ]:
#Droop rows
import pandas as pd
import numpy as np
#Sample dataset
df = pd.DataFrame({'Age': [25,30,np.nan,40,35],
    'Department': ['HR', 'Finance', np.nan,'Finance', 'IT']})
#Display Original Dataset
print("Original Dataset")
print(df)
df_drop_rows = df.dropna()
print(df_drop_rows)



Original Dataset
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN        NaN
3  40.0    Finance
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
3  40.0    Finance
4  35.0         IT


In [ ]:
#Drop columns
import pandas as pd
import numpy as np
#Sample dataset
df = pd.DataFrame({'Age': [25,30,np.nan,40,35],
    'Department': ['HR', 'Finance', np.nan,'Finance', 'IT']})
#Display Original Dataset
print("Original Dataset")
print(df)
df_drop_columns = df.dropna(axis=1)
print("After dropping columns:\n",df_drop_columns)

Original Dataset
    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN        NaN
3  40.0    Finance
4  35.0         IT
After dropping columns:
 Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'ID': [1, 2, 2, 4, 1, 1],
    'Name': ['Alice', 'Bob', 'Bob', 'Charlie', 'David', 'David'],
    'Age': [35, 30, 30, 40, 25, 25]
})

print("Original Data:\n", df)

# Remove exact duplicate rows (all columns match)
df_exact = df.drop_duplicates()
print("\nAfter Exact Match Removal:\n", df_exact)

# Remove duplicates based on ID only, keeping the first occurrence
df_by_id = df.drop_duplicates(subset='ID', keep='first')
print("\nAfter ID-based Duplicate Removal:\n", df_by_id)

Original Data:
    ID     Name  Age
0   1    Alice   35
1   2      Bob   30
2   2      Bob   30
3   4  Charlie   40
4   1    David   25
5   1    David   25

After Exact Match Removal:
    ID     Name  Age
0   1    Alice   35
1   2      Bob   30
3   4  Charlie   40
4   1    David   25

After ID-based Duplicate Removal:
    ID     Name  Age
0   1    Alice   35
1   2      Bob   30
3   4  Charlie   40


In [ ]:
#Subset Based Removal
import pandas as pd
df = pd.DataFrame({
    'ID': [1, 2, 2, 3, 4, 4, 1],
    'Name': ['Alice', 'Bob', 'Charlie', 'Eve', 'Eve', 'Alice'],
    'Age': [25, 30, 35, 40, 35, 25]
})
print("Original Data:\n",df)
df_subset_id

In [ ]:
#Case Normalization
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'BoB', 'charlie','DAVID']})
#Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
#Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()
print(df)


      Name Name_lower Name_upper
0   Alice,     alice,     ALICE,
1      BoB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID
